baseURL = "https://blog-dsalazar.vercel.app/"
languageCode = "es-ES"
title = "Mi blog"
theme = "ezhil"

copyright = "Â© 2021"

# Enable syntax highlighting.
pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Your Google analytics code.
googleAnalytics = "TU_CODIGO_DE_ANALYTICS"
# Your Disqus sortname.
disqusShortname = "disqus_g3DNQkKnvy"

# Number of posts to show in recent posts list (Optional). Defaults to 10.
paginate = 10

[params]
    # Blog subtitle which appears below blog title. Supports markdown.
    subtitle = "Blog de programaciÃ³n o eso creo ðŸ˜ƒ"
    # Content types which are included in home page recent posts list.
    mainSections = ["posts"]
    # Content types which are excludes Disqus comments.
    disableDisqusTypes = ["page"]
    # If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
    featherIconsCDN = true

    

# Main menu which appears below site header.
[[menu.main]]
name = "Inicio"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "FAQ"
url = "/faq"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5

# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).
[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/mrgold92"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = ""

# Enable tags.
[taxonomies]
   tag = "tags"
